# PostgreSQL
#   Ensure the PostgreSQL gem is defined in your Gemfile
#   gem 'pg'
development: 
  adapter: postgresql 
  encoding: utf8 
  database: recovery_on_rails_development 
  username: recovery_on_rails
  host: localhost
  pool: 5
  port: 5432
  password: recovery_on_rails